### ISSUE TITLE
create logo for kpopstop

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#10]

**Comment by zaynab-j** [comment]
I made this design for the logo. Don't think it's good, but thought I would share it anyways. I have included the different versions of it to this google drive folder:

https://drive.google.com/drive/folders/1643Zy38R6A4qcz75gYaGCXM9onhlfGPv?usp=sharing

I also included the Ai file to the simple version of the design as well as the font used if someone would like to try creating a different variation of it with different colors/arrangement.

**Comment by hyang-gi** [comment]
<img width="1043" alt="Screenshot 2023-02-23 at 11 43 34" src="https://user-images.githubusercontent.com/84595887/220896525-8965aeff-2f7e-4fe8-bb95-347e973894fd.png">
