### ISSUE TITLE
Brand colours for kpopstop

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#14]

**Comment by ganderson35** [comment]
https://assets.adobe.com/id/urn:aaid:sc:EU:4e140809-9dad-4f75-9071-df9cf513a102?view=difile

**Comment by ganderson35** [comment]
^ ai file with draft of color palette, typography and logo designs

**Comment by hyang-gi** [comment]
Differentiate the colours based on the content. 
For now, we have the ones for the buildings, we still need something for the brand - kpopstop (even if it's not heavily used)
