### ISSUE TITLE
list of images / graphics / illustrations needed 

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#17]
**Images**

- company buildings - done
- band logos - done
- company logos - done
- website logo - done

**icons**
- social media
- filters 

Note: different sizes (svg type should take care of this)

**Comment by zaynab-j** [comment]
Update:  The following images have been obtained:
- company buildings
- band logos
- company logos

The images can be found through this link: 
https://drive.google.com/drive/folders/13ly9LxgRr-7s8RQFkQZbHyy971wS3BFq?usp=share_link
