### ISSUE TITLE
draft for accessibility plan (deliverable 5) 

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#18]

**Comment by MollyHM** [comment]
I've started a working document for our accessibility goals. 

[Deliverable 5-Accessibility Needs.docx](https://github.com/hyang-gi/kpopstop/files/10831808/Deliverable.5-Accessibility.Needs.docx)

**Comment by MollyHM** [comment]
Free WCAG 2.1 AA Compliance Summary of Your Website:
https://www.boia.org/products/free-wcag-2-0-aa-report/
