### ISSUE TITLE
create mid fidelity mockups for mobile view

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#20]

**Comment by zaynab-j** [comment]
Done. Here is the link:
 [https://drive.google.com/file/d/1G1p7cvIa9NrBt96cDKMf5aecke-CSwiF/view?usp=sharing](url)

**Comment by zaynab-j** [comment]
Done. 

![Mobile Mock Ups - Sample Pages](https://user-images.githubusercontent.com/119420415/221373561-ee49c67a-9d42-4149-bcdc-13c0b88d65ca.png)
