### ISSUE TITLE
user flows required for the website

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#4]
The purpose of user flows is to act like the user, here's a list of tasks we discussed. Please add more in the comments below if I've missed any. 

1. Look at the company buildings
2. Check out the bands 
3. Find various available tours (with applicable filters)
4. Contact the site admin with inquiry/issues
5. Search the location of the building based on the google maps
6. Contact regarding accessibility issues
7. Visit the help section

**Comment by hyw007726** [comment]
Thank you Nikhat!
