### ISSUE TITLE
content for the trending page 

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#46]

**Comment by ganderson35** [comment]
Links to external news articles related to the buildings for the in the news part of the trending page: 

https://www.wallpaper.com/architecture/yg-entertainment-headquarters-unstudio-seoul-south-korea 

https://www.scmp.com/lifestyle/k-pop/article/3175839/how-dutch-architects-blackpink-record-labels-seoul-hq-balanced-its?module=perpetual_scroll_0&pgtype=article&campaign=3175839 

https://koreajoongangdaily.joins.com/2022/11/15/entertainment/kpop/Korea-Kpop-Seoul/20221115164643775.html 

https://www.architecturaldigest.in/story/tour-k-pops-stunning-new-headquarters-seoul/ 

https://www.archdaily.com/978531/yg-headquarters-unstudio 

https://koreajoongangdaily.joins.com/2021/03/22/culture/artsDesign/Big-Hit-Entertainment-HYBE-Yongsan/20210322160000459.html 

https://inhabitat.com/unstudio-designs-k-pop-entertainments-new-hq-in-seoul/ 

https://www.tatlerasia.com/homes/architecture-design/inside-yg-entertainment-new-headquarters-in-seoul-unstudio
