### ISSUE TITLE
add some text before the images in Buildings Gallery

### ISSUE THREAD

**Issue by hyang-gi** [hyang-gi/kpopstop#81]
We need this because at the moment the users won't know what exactly these images are or what the building is highlighting.

**Comment by zaynab-j** [comment]
@hyang-gi : Here is some text for each buildings gallery page that includes brief descriptions of the images included:

JYP:

JYP Entertainment's new building, located in Seongnae-dong District of Seoul, is made of eco-friendly materials and has an estimated value of 43 billion won. It consists of dance studios, vocal practice rooms, and a band room. The interior design is influenced by Western artists such as Michael Jackson, Bobby Brown, and Madonna, with 15 rooms inspired by musicians from the 70s, 80s, and 90s. The top floors of the building houses recording studios, and the rooftop garden offers a perfect view of the city.

YG:

YG Entertainment unveiled its new futuristic-looking building in 2021, designed by UNStudio. It has nine top floors, five additional floors underground, and an internal bridge that connects it to the old YG Building. The exterior is designed to resemble an "urban speaker" with glass and aluminium panels, and BIPV (building-integrated photovoltaics) solar cells are integrated in the south-facing facade and on the roof. The interior design is white tones and geometric lines, with large open spaces and high ceilings. The structure also includes capsule-style meeting rooms and work zones with full glass windows, and amenities such as a two-story auditorium, seven large dance practice rooms, seven recording studios outfitted with cutting-edge technology, and 30 personal studios.

SM:

SM Entertainment's modern and sleek-looking building is located in the fashionable neighbourhood Seongsu-dong within the Acro Seoul Forest complex. It features a modern interior with windows and open space for employees to socialise, a back area for coffee machines and snacks, and an in-house garden for relaxing. On November 17th, 2022, SM added a new space called the 'Kwangya Seoul' which provides an SM Town shopping experience and digital services. The store was designed to offer visiting fans an experience of living in the SM Entertainment Universe, recreating the metaverse with clear OLED display panels.

**Comment by hyang-gi** [comment]
@zaynab-j Thank you!

[Commit](https://github.com/hyang-gi/kpopstop/commit/e24ebd6e96b6d6bff638b681fcba1beb40c3ce80) with changes.
